CalculatorTech/CalculatorTech/Models/TabelaDitribuicaoFrequencia/RegistroTabela.cs
namespace CalculatorTech.Models.TabelaDitribuicaoFrequencia
{
    public class RegistroTabela
    {
        public double DeClasse { get; set; }

        public double AteClasse { get; set; }

        public int FrequenciaAbsoluta { get; set; }

        public double FrequenciaRelativa { get; set; }

        public int FrequenciaAbsolutaAcumulada { get; set; }

        public double FrequenciaRelativaAcumulada { get; set; }
    }
}

CalculatorTech/CalculatorTech/Models/TabelaDitribuicaoFrequencia/TabelaDistribuicaoFrequencia.cs
namespace CalculatorTech.Models.TabelaDitribuicaoFrequencia
{
    public class TabelaDistribuicaoFrequencia
    {
        public TabelaDistribuicaoFrequencia()
        {
            RegistrosTabela = new List<RegistroTabela>();
            Valores = new List<string>();
        }



        public List<RegistroTabela> RegistrosTabela { get; set; }

        public List<string> Valores { get; set; }


    }
}

CalculatorTech/CalculatorTech/Controllers/EstatisticaController.cs
using CalculatorTech.Models;
using CalculatorTech.Models.TabelaDitribuicaoFrequencia;
using CalculatorTech.Services;
using CalculatorTech.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace CalculatorTech.Controllers
{
    public class EstatisticaController : Controller
    {
        private readonly IEstatisticaService _estatisticaService;

        public EstatisticaController(IEstatisticaService estatisticaService)
        {
            _estatisticaService = estatisticaService;
        }

        public IActionResult DistribuicaoFrequencia( bool adicionarLinha, string[] valor)
        {
            if (TempData["numeroLinhasGridEntrada"] == null)
            {
                TempData["numeroLinhasGridEntrada"] = 5;
            };
            if (adicionarLinha)
            {
                TempData["numeroLinhasGridEntrada"] = (int)TempData["numeroLinhasGridEntrada"] + 1;
            }
            
            if (valor.Length != 0)
            { 
                TabelaDistribuicaoFrequencia tabelaDistribuicaoFrequencia = new TabelaDistribuicaoFrequencia();
                tabelaDistribuicaoFrequencia = _estatisticaService.RetornarTabelaDistribuicaoDeFrequencia(valor);
                tabelaDistribuicaoFrequencia.Valores = valor.ToList();
                return View(tabelaDistribuicaoFrequencia);
            }
            

            return View();
        }

        public RedirectToActionResult AdicionarLinhasGrid()
        {

            return RedirectToAction("DistribuicaoFrequencia", new { adicionarLinha = true});
        }


    }
}

CalculatorTech/CalculatorTech/Views/Estatistica/DistribuicaoFrequencia.cshtml
@using CalculatorTech.Models.TabelaDitribuicaoFrequencia
@model TabelaDistribuicaoFrequencia

<h2>Calculadora de distribuição de frequência</h2>
<br>
<br>
<p class="font-weight-normal">Insira os números de entrada para a criação da tabela de frequência:</p>
<br>

<form asp-action="DistribuicaoFrequencia">
	@{
		if (Model == null)
		{
			<div class="row linhasGrid">
				@for (int linha = 1; linha <= (int)TempData.Peek("numeroLinhasGridEntrada"); linha++)
				{
					<div class="col-2">
						<input type="number" name="valor" class="form-control entradaValores" value="" />
					</div>
					<div class="col-2">
						<input type="number" name="valor" class="form-control entradaValores" />
					</div>
					<div class="col-2">
						<input type="number" name="valor" class="form-control entradaValores" />
					</div>
					<div class="col-2">
						<input type="number" name="valor" class="form-control entradaValores" />
					</div>
					<div class="col-2">
						<input type="number" name="valor" class="form-control entradaValores" />
					</div>
					<div class="col-2">
						<input type="number" name="valor" class="form-control entradaValores" />
					</div>
				}
			</div>
		}
		else
		{
			<div class="row linhasGrid">
				@foreach (var valor in Model.Valores)
				{

					<div class="col-2">
						<input type="number" name="valor" class="form-control entradaValores" value="@valor" />
					</div>

				}
			</div>
		}

	}
	<br>
	<div class="row">
		<div class="col-1 form-group">
			<input type="submit" value="Calcular" class="btn btn-success" />
		</div>
		<div class="col-2">
			<p class="button">
				<a class="btn btn-primary" asp-controller="Estatistica"
				   asp-action="AdicionarLinhasGrid">
					Adicionar linha
				</a>
			</p>
		</div>

	</div>


</form>





@if (@Model != null)
{
	<table class="table">
		<thead>
			<tr>
				<th scope="col">Classes</th>
				<th scope="col">Frequência absoluta</th>
				<th scope="col">Frequência relativa</th>
				<th scope="col">Frequência absoluta acumulada</th>
				<th scope="col">Frequência relativa acumulada</th>
			</tr>
		</thead>
		<tbody>
			@foreach (var item in Model.RegistrosTabela)
			{
				<tr>
					<td>@item.DeClasse - @item.AteClasse</td>
					<td>@item.FrequenciaAbsoluta</td>
					<td>@item.FrequenciaRelativa</td>
					<td>@item.FrequenciaAbsolutaAcumulada</td>
					<td>@item.FrequenciaRelativaAcumulada</td>
				</tr>
			}

		</tbody>
	</table>
}

<div class="border border-primary-subtle rounded-2 p-3 containerTextoPagina">

	<p class="tituloTextoPagina"> Distribuição de frequência</p>

	<p class="textoPagina">
		A distribuição de frequência é uma ferramenta estatística fundamental que organiza dados em categorias distintas e apresenta a frequência com que cada categoria ocorre.
		Essa análise é crucial para compreender a distribuição e padrões subjacentes nos dados, proporcionando uma visão mais clara do conjunto de informações.
	</p>

	<p class="textoPagina">
		Uma tabela de distribuição de frequência é uma forma organizada de apresentar dados estatísticos, especialmente quando lidamos com conjuntos de dados extensos. Ela organiza e resume a informação, facilitando a análise e interpretação dos dados.
	</p>



	<p class="tituloTextoPagina">Como Montar uma Tabela de Distribuição de Frequência:</p>

	<p class="textoPagina">
		Coleta de Dados:<br />
		O primeiro passo é coletar os dados brutos. Eles podem ser obtidos por meio de observações, experimentos, pesquisas ou qualquer outra fonte relevante.
	</p>
	

	<p class="textoPagina">
		Organização dos Dados:<br />
		Organize os dados em ordem crescente ou decrescente, dependendo da natureza da variável. Essa organização facilita a análise e interpretação dos resultados.
	</p>
	

	<p class="textoPagina">
		Determinação do Número de Classes (K):<br />
		Escolha o número de classes que será utilizado na distribuição. Um bom ponto de partida é utilizar a regra de Sturges, que sugere K = 1 + log2(N), onde N é o número total de observações.
	</p>
	
	<p class="textoPagina">
		Intervalos de Classes:<br />
		Calcule a amplitude das classes dividindo a diferença entre o maior e o menor valor pelos intervalos desejados. Arredonde para o número inteiro mais próximo para obter os limites das classes.
	</p>
	

	<p class="textoPagina">
		Construção da Tabela:<br />
		Crie uma tabela com colunas para as classes, limites de classe, frequência absoluta (número de observações em cada classe) e frequência relativa (percentual ou proporção em relação ao total).
	</p>
	

	<p class="textoPagina">
		Cálculos Adicionais:<br />
		Calcule a frequência acumulada (soma das frequências absolutas ou relativas até uma determinada classe) e, se necessário, a frequência relativa acumulada.
	</p>
	


	<p class="tituloTextoPagina">Exemplo prático:</p>

	<p class="textoPagina">
		Suponha que temos as seguintes idades de um grupo de pessoas (em anos): 21, 23, 25, 28, 30, 32, 34, 36, 39, 41.
		<br />
		Organização:
		<br />
		21, 23, 25, 28, 30, 32, 34, 36, 39, 41.
		<br />
		<br />
		Número de Classes (K):
		<br />
		Utilizando a regra de Sturges, K = 1 + log2(10) ≈ 4 classes.
		<br />
		<br />
		Intervalos de Classes:
		<br />
		Amplitude = (41 - 21) = 20 / 4 = 5. Classes: 21-25, 26-30, 31-35, 36-40, 41-45.
		<br />
		<br />
		<img src="/img/tabelaDistFreq.png" />
	</p>
</div>

CalculatorTech/CalculatorTech/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CalculatorTech</title>
    <!--<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CalculatorTech.styles.css" asp-append-version="true" />
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7905751619865637"
     crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <h1>
             <a class="link-dark link-offset-2 link-underline link-underline-opacity-0" asp-area="" asp-controller="Estatistica" asp-action="DistribuicaoFrequencia">
                   <img src="/img/icon-converter.png" alt="Logo" width="55" height="49" class="d-inline-block align-text-top">
                   CalculatorTech
             </a>
        </h1>
      
    

        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
            <div class="container-fluid">
                    
                
                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">Estatística</a>
                            <ul class="dropdown-menu" >
                                <li><a class="dropdown-item"  asp-area="" asp-controller="Estatistica" asp-action="DistribuicaoFrequencia">Distribuição de frequência</a></li>
                            </ul>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CalculatorTech
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <!--<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>